service: sls-demo

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: us-east-1

  # 'iamRoleStatement' defines the permission policy for the Lambda function.
  # In this case Lambda functions are granted with permissions to access DynamoDB.
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"

functions:

  customer:
    handler: customer.main
    events:
      - http:
          method: get
          path: customer
          request:
            template:
              application/json: '{ "ACCT_NUM" : "$input.params(''ACCT_NUM'')" }'
          cors: true
          # integration: lambda
          authorizer:
            name: authorizer
            arn: arn:aws:cognito-idp:us-east-1:466357709346:userpool/us-east-1_wttsX9YPg

  invoice:
    handler: invoice.main
    events:
      - http:
          method: get
          path: invoice
          request:
            template:
              application/json: >
                {
                  "ACCT_NUM" : "$input.params('some_data')",
                  "REVENUE_MTH": "$input.params('some_data')"
                  "REVENUE_YR": "$input.params('some_data')"
                }
          cors: true
          # integration: lambda
          authorizer:
            name: authorizer
            arn: arn:aws:cognito-idp:us-east-1:466357709346:userpool/us-east-1_wttsX9YPg
  # update:
    # Defines an HTTP API endpoint that calls the main function in update.js
    # - path: url path is /notes/{id}
    # - method: PUT request
    # handler: update.main
    # events:
    #   - http:
    #       path: user/{id}
    #       method: put
    #       cors: true
    #       integration: lambda
    #       authorizer:
    #         name: authorizer
    #         arn: arn:aws:cognito-idp:us-east-1:466357709346:userpool/us-east-1_wttsX9YPg
  # create:
  #   handler: create.main
  #   events:
  #     - http:
  #         path: users
  #         method: post
  #         cors: true
  #         integration: lambda
  #         authorizer:
  #           name: authorizer
  #           arn: arn:aws:cognito-idp:us-east-1:466357709346:userpool/us-east-1_wttsX9YPg

